{% set name = "ernie" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: "{{ version }}"

source:
  git_url: https://github.com/finkler/ernie.git
  git_rev: master
  git_depth: 1

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv "
  noarch: python
  include_recipe: False

requirements:
  host:
    - pip
    - python
  run:
    - python
    - gdal
    - matplotlib
    - numpy

test:
  imports:
    - ernie

about:
  home: https://github.com/finkler/ernie
  license: MIT
  license_family: MIT
  summary: ernie for BERT

